---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by koris.
--- DateTime: 5/23/2020 8:56 AM
---

require('scripts/globals/spells')

tpz.cInterfaceFunctions = tpz.cInterfaceFunctions or {}

function tpz.cInterfaceFunctions.castSpell(spellId, spellObj, casterObj, targetObj)
    local spell = tpz.spells[spellId]
    local ret, error_msg

    if spell ~= nil then
        ret = spell(spellObj, casterObj, targetObj)
    else
        error_msg = "[Lua] Warning: Attempt to cast a spell that does not exist: SpellId(" .. spellId .. ")"
    end

    return ret, error_msg
end